blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/monkeyking-hq/universal-code/discussions
    about: Please use Discussions for proposals, critiques, questions, and changes to the Universal Code principles.
